server:
  port: 9899

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  dataSource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      url: jdbc:mysql://101.132.157.3:3377/readWriteDemo?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
      username: pMpgk2Lfb5ZactK5LoK5Yg==
      password: 2DU2ZWsYF36sjC88PM2OQA==
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      url: jdbc:mysql://120.55.195.145:3377/readWriteDemo?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
      username: pMpgk2Lfb5ZactK5LoK5Yg==
      password: 2DU2ZWsYF36sjC88PM2OQA==
